# Generated by Django 4.1.4 on 2022-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapp', '0002_postmodel_created_date_postmodel_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
